config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: :show do
    get 'posts'
    get 'photos'
    get 'friends'
    get 'likes'
  end

  get 'profile/edit', to: 'users#edit_profile', as: :edit_profile
  patch 'profile/update', to: 'users#update_profile', as: :update_profile

  get '/friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :posts do
    resources :comments, only: [:new, :edit]
  end

  resources :comments, only: [:create, :update, :destroy]
  get 'posts/:comment_id/new', to: 'comments#new_reply', as: 'new_reply'
  get 'posts/:comment_id/edit', to: 'comments#edit_reply', as: 'edit_reply'

  resources :likes, only: [:create, :destroy]

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  delete 'unfriend', to: 'friendships#destroy', as: 'destroy_friendship'

  get 'about', to: 'static_pages#about'
  get 'search', to: 'static_pages#search'
  get 'odin/invincible', to: 'static_pages#odin_invincible'
  get 'odin/immutable', to: 'static_pages#odin_immutable'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :bigint           not null, primary key
#  body             :text             not null
#  author_id        :bigint           not null
#  commentable_type :string           not null
#  commentable_id   :bigint           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Comment < ApplicationRecord
  include ActionView::Helpers::DateHelper
  include ElapsedTime

  belongs_to :author, class_name: :User
  belongs_to :commentable, polymorphic: true
  has_many :comments,
    -> { order(:created_at) },
    as: :commentable,
    dependent: :destroy

  has_many :likes,
    as: :likable,
    dependent: :destroy

  validates :body, presence: true

  def history
    simple_elapsed_time(created_at)
  end

  def get_post_or_photo_id
    parent = commentable
    parent = parent.commentable while parent.class == Comment
    parent.id
  end
  
  def unnested_commentable_id
    if commentable.class == Comment
      commentable.commentable_id
    else
      commentable_id
    end
  end

  def get_placeholder
    if commentable.class == Comment
      "Reply to #{commentable.author.name}..."
    else
      'Write a comment...'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.includes(
                   :likes,
                   comments: [
                     :likes,
                     author: { avatar_attachment: :blob},
                     comments: [
                        :likes,
                        author: { avatar_attachment: :blob }
                     ]
                   ]
                 )
                .find(params[:post_id])
    @autofocus = true;
    render 'posts/show'
  end

  def create
    comment = current_user.comments.build(comment_params)
    flash.alert = "Error: #{comment.errors.full_messages.join}" unless comment.save
    redirect_to post_url(comment.get_post_or_photo_id, anchor: "comment-#{comment.id}")
  end

  def edit
    @post = Post.includes(
                   :likes,
                   comments: [
                     :likes,
                     author: { avatar_attachment: :blob},
                     comments: [
                        :likes,
                        author: { avatar_attachment: :blob }
                     ]
                   ]
                 )
                .find(params[:post_id])
    @edit = params[:id].to_i
    render 'posts/show'
  end

  def update
    comment = Comment.find(params[:id])
    flash.alert = "Error: #{comment.errors.full_messages.join}" unless comment.update(comment_params)
    redirect_to post_url(comment.get_post_or_photo_id, anchor: "comment-#{comment.id}")
  end

  def new_reply
    @comment = Comment.find(params[:comment_id])
    @post = Post.includes(
                   :likes,
                   comments: [
                     :likes,
                     author: { avatar_attachment: :blob},
                     comments: [
                        :likes,
                        author: { avatar_attachment: :blob }
                     ]
                   ]
                 )
                .find(@comment.get_post_or_photo_id)
    @reply_to = params[:comment_id].to_i
    render 'posts/show'
  end

  def destroy
    comment = Comment.find(params[:id])
    url = post_url(comment.get_post_or_photo_id)
    comment.destroy
    redirect_to url
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/views/comments/_comment.html.erb
<% reply = comment.commentable_type == 'Comment' %>

<div id='comment-<%= comment.id %>' class='comment'>
  <%= avatar_thumbnail(comment.author, 'comment-avatar') %>

  <div class='comment-wrapper'>
    <div class='comment-main <%= 'full-width' if edit == comment.id %>'>
      <div class='comment-bubble'>
        <div class='comment-header'>
          <%= link_to comment.author.name, comment.author, class: 'author' %>
          <div class='comment-author-links'>
            <%= link_to 'Edit |', edit_post_comment_path(comment.get_post_or_photo_id, comment) if comment.author == current_user && edit != comment.id %>
            <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } if comment.author == current_user %>
          </div>
        </div>
        <% if comment.author == current_user && edit == comment.id %>
          <%= render 'comments/form', comment: comment, submit: 'Update', autofocus: true %>
        <% else %>
          <%= comment.body %>
        <% end %>
      </div>
      <div class='comment-footer'>
        <div class='comment-controls'>
          <% like = comment.likes.find { |like| like.user_id == current_user.id } %>
          <span><%= comment.history %></span>
          <%= link_to 'Reply', new_reply_path(comment.id), class: 'comment-links' %>
          <% if like %>
            <%= button_to 'Unlike', like_path(like), method: :delete, class: 'hidden-button comment-links'%>
          <% else %>
            <%=  button_to 'Like', likes_path, params: { like: { user_id: current_user, likable_id: comment.id, likable_type: 'Comment' } }, class: 'hidden-button comment-links' %>
          <% end %>
        </div>
        <% comment_likes = comment.likes.size %>
        <% if comment_likes > 0 %>
          <div class='comment-like-container'>
            <ion-icon class='comment-like' name="heart"></ion-icon><!--
            --><span><%= comment.likes.size %></span>
          </div>
        <% end %>
      </div>
    </div>
    <% unless reply %>
      <div class='comment-replies'>
        <% parent_comment = false %>
        <% comment.comments.order(:created_at).each do |comment| %>
            <% if comment.author == current_user && edit == comment.id %>
              <div class='comment-reply'>
                <%= avatar_thumbnail(comment.author, 'comment-avatar') %>
                <%= render 'comments/form', comment: comment, submit: 'Update', autofocus: true %>
              </div>
            <% else %>
              <%= render comment, comment: comment, edit: false, reply_to: reply_to %>
            <% end %>
            <% parent_comment = comment if reply_to == comment.id %>
        <% end %>
        <% if parent_comment %>
            <div class='comment-reply'>
              <%= avatar_thumbnail(current_user, 'comment-avatar') %>
              <div class='full-width'><%= render 'comments/form', comment: parent_comment.comments.build, submit: 'Reply', autofocus: true, nested: true %></div>
            </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<% nested ||= false %>

<%= form_with(model: comment, local: true) do |form| %>
  <div class='comment-form'>
    <% unless comment.persisted? %>
      <%= form.hidden_field :commentable_id, value: (nested ? comment.unnested_commentable_id : comment.commentable_id) %>
      <%= form.hidden_field :commentable_type, value: comment.commentable_type %>
    <% end %>

    <%= form.text_area :body, rows: '3', placeholder: comment.get_placeholder, autofocus: autofocus %>
    <div class="submit-wrapper">
      <%= link_to 'Cancel', post_url(comment.get_post_or_photo_id), class: 'comment-submit comment-cancel' unless submit == 'Comment'%>
      <%= form.submit submit, class: 'comment-submit' %>
    </div>
  </div>
<% end %>