config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: :show do
    get 'posts'
    get 'photos'
    get 'friends'
    get 'likes'
  end

  get 'profile/edit', to: 'users#edit_profile', as: :edit_profile
  patch 'profile/update', to: 'users#update_profile', as: :update_profile

  get '/friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :posts do
    resources :comments, only: [:new, :edit]
  end

  resources :comments, only: [:create, :update, :destroy]
  get 'posts/:comment_id/new', to: 'comments#new_reply', as: 'new_reply'
  get 'posts/:comment_id/edit', to: 'comments#edit_reply', as: 'edit_reply'

  resources :likes, only: [:create, :destroy]

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  delete 'unfriend', to: 'friendships#destroy', as: 'destroy_friendship'

  get 'about', to: 'static_pages#about'
  get 'search', to: 'static_pages#search'
  get 'odin/invincible', to: 'static_pages#odin_invincible'
  get 'odin/immutable', to: 'static_pages#odin_immutable'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  name                   :string           default(""), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  location               :string
#  education1             :string
#  education2             :string
#  education3             :string
#  occupation             :string
#  website                :string
#  birthday               :date
#  provider               :string
#  uid                    :string
#
require 'open-uri'

class User < ApplicationRecord

  def self.from_omniauth(auth)
    oauth_user = where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      if auth.info.image
        downloaded_image = URI.open(auth.info.image)
        user.avatar.attach(io: downloaded_image,
                           filename: "image-#{Time.now.strftime("%s%L")}",
                           content_type: downloaded_image.content_type)
      end
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"] ||
         data = session["devise.github_data"] && session["devise.github_data"]["info"]
        user.name = data["name"] if user.name.blank?
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook github]

  validates :name, :email, presence: true

  has_many :posts,
    foreign_key: :author_id,
    inverse_of: :author,
    dependent: :destroy
  
  has_many :likes,
    dependent: :destroy

  has_many :comments,
    foreign_key: :author_id,
    inverse_of: :author,
    dependent: :destroy

  has_many :friend_requests,
    foreign_key: :requester_id,
    inverse_of: :requester,
    dependent: :destroy

  has_many :requested_friends,
    through: :friend_requests,
    source: :recipient

  has_many :friend_invitations,
    foreign_key: :recipient_id,
    class_name: :FriendRequest,
    inverse_of: :recipient,
    dependent: :destroy

  has_many :requesting_friends,
    through: :friend_invitations,
    source: :requester

  has_many :friendships,
    ->(user) { unscope(:where).where('friend_a_id = ? OR friend_b_id = ?', user.id, user.id) },
    dependent: :destroy

  has_one_attached :avatar

  def friends
    join_statement = <<-SQL
      INNER JOIN friendships
        ON (friendships.friend_a_id = users.id OR friendships.friend_b_id = users.id)
        AND (friendships.friend_a_id = #{id} OR friendships.friend_b_id = #{id})
    SQL
    User.joins(join_statement)
        .where.not(id: id)
  end

  def friends_sql
    # SQL implentation, but returns array instead of ActiveRecord Relation
    User.find_by_sql(<<~SQL)
      SELECT users.*
      FROM users
      INNER JOIN friendships
        ON (friendships.friend_a_id = users.id OR friendships.friend_b_id = users.id)
        AND (friendships.friend_a_id = #{id} OR friendships.friend_b_id = #{id})
      WHERE users.id <> #{id};
    SQL
  end

  def non_friends_and_pending
    join_statement = <<-SQL
      LEFT OUTER JOIN friendships
        ON (friendships.friend_a_id = users.id OR friendships.friend_b_id = users.id)
        AND (friendships.friend_a_id = #{id} OR friendships.friend_b_id = #{id})
      LEFT OUTER JOIN friend_requests
        ON friend_requests.requester_id = users.id
        AND friend_requests.recipient_id = #{id}
      SQL
    
    User.joins(join_statement)
        .where( friendships: { id: nil }, friend_requests: { id: nil} )
        .where.not(id: id)
  end

  def no_contacts
    join_statement = <<-SQL
      LEFT OUTER JOIN friendships
        ON (friendships.friend_a_id = users.id OR friendships.friend_b_id = users.id)
        AND (friendships.friend_a_id = #{id} OR friendships.friend_b_id = #{id})
      LEFT OUTER JOIN friend_requests
        ON (friend_requests.requester_id = users.id OR friend_requests.recipient_id = users.id)
        AND (friend_requests.requester_id = #{id} OR friend_requests.recipient_id = #{id})
      SQL
    
    User.joins(join_statement)
        .where( friendships: { id: nil }, friend_requests: { id: nil} )
        .where.not(id: id)
  end

  def set_avatar!(photo_number = rand(25))
    filename = "#{photo_number}.png"
    path = Rails.root.join("app/assets/images/Default Avatars", filename)
    File.open(path) do |io|
      self.avatar.attach(io: io, filename: filename, content_type: 'image/png')
    end
    save!
  end

  def formatted_birthday
    birthday.strftime('%B %-d')
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: [:facebook, :github]

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    after_create_callbacks if @user.new_record? && @user.save

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      flash.alert = "Error: #{@user.errors.full_messages.join}"
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    after_create_callbacks if @user.new_record? && @user.save

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  private

  def after_create_callbacks
    create_friend_invitations
    ensure_avatar
    send_welcome_email
    send_new_sign_up_email
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  after_action :create_friend_invitations, :ensure_avatar, :send_welcome_email, :send_new_sign_up_email, only: :create, if: -> { @user.persisted? }

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    if(current_user.email == 'odin@example.com')
      send_odin_update_email
      redirect_to odin_immutable_url
    else
      super
    end
  end

  # DELETE /resource
  def destroy
    if(current_user.email == 'odin@example.com')
      send_odin_delete_email
      redirect_to odin_invincible_url
    else
      super
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
  end

  def posts
    @user = User.find(params[:user_id])
    @posts = Post.where(author: @user)
                 .order(created_at: :desc)
                 .with_attached_photo
                 .includes(:likes, :author, comments: :comments)
  end

  def photos
    @user = User.find(params[:user_id])
    @posts = @user.posts
                  .joins(:photo_attachment)
                  .order(created_at: :desc)
                  .with_attached_photo
  end

  def likes
    @user = User.find(params[:user_id])
    liked_posts_ids = Like.where(user_id: @user.id, likable_type: "Post")
                          .pluck(:likable_id)
    @posts = Post.where('id IN (?)', liked_posts_ids)
                 .with_attached_photo
                 .includes(:likes, comments: :comments, author: { avatar_attachment: :blob })
                 .order(created_at: :desc)
  end

  def friends
    @user = params[:user_id] ? User.find(params[:user_id]) : current_user
    @friends = @user.friends
                    .with_attached_avatar
                    .order(:name)
  end

  def friend_requests
    @invitations = current_user.friend_invitations
                               .includes(requester: { avatar_attachment: :blob} )
                               .order('users.name')
  end

  def find_friends
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    current_user.update(profile_params)
    redirect_to current_user
  end

  private

  def profile_params
    params.require(:user)
          .permit(:avatar, :location, :birthday, :occupation,
                  :education1, :education2, :education3, :website)
  end
end

app/views/users/edit_profile.html.erb
<h3>Edit Profile</h3>
<%= form_with(model: @user, local: true, url: update_profile_path) do |form| %>
  <div class='edit-profile-container'>
  
    Update Profile Picture:
    <%= form.file_field :avatar, direct_upload: true %>

    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, class: 'edit-profile-avatar' %>
    <% end %>

    <br>
    <div class='profile-edit-fields'>
      <div class="field">
        <label for='location'>Location</label>
        <%= form.text_field :location %>
      </div>

      <div class="field">
        <label for='education1'>Education</label>
        <%= form.text_field :education1 %>
      </div>

      <div class="field">
        <label for='education2'>Education</label>
        <%= form.text_field :education2 %>
      </div>

      <div class="field">
        <label for='education3'>Education</label>
        <%= form.text_field :education3 %>
      </div>

      <div class="field">
        <label for='occupation'>Occupation</label>
        <%= form.text_field :occupation %>
      </div>

      <div class="field">
        <label for='website'>Website</label>
        <%= form.text_field :website %>
      </div>

      <div class="field">
        <label for='birthday'>Birthday</label>
        <%= form.date_select :birthday, discard_year: true, prompt: true %>
      </div>
    </div>

    <div class="submit-wrapper">
      <%= form.submit 'Update Profile', class: 'update-profile' %>
    </div>
  </div>
<% end %>

app/views/users/find_friends.html.erb
<h3>Find Friends</h3>

<div class='friends-container'>
  <% pending_requests = current_user.requested_friends.pluck(:id) %>
  <% current_user.non_friends_and_pending.with_attached_avatar.order(:name).each do |friend| %>
    <div class='friend-full-row'>
      <div class='friend-row'>
        <%= avatar_thumbnail(friend, 'friend-list-avatar') %>
        <%= link_to friend.name, user_path(friend) %>
      </div>
      <% if !!pending_requests.delete(friend.id) %>
        <i class="far fa-clock"></i>
      <% else %>
        <%= button_to friend_requests_path, method: :post, class: 'add-friend', params: { recipient_id: friend.id } do %>
          <i class="fas fa-user-plus"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/friend_requests.html.erb
<h3>Friend Requests</h3>

<div class='friends-container'>
  <% @invitations.each do |invitation| %>
    <div class='friend-full-row'>
      <div class='friend-row'>
        <%= avatar_thumbnail(invitation.requester, 'friend-list-avatar') %>
        <%= link_to invitation.requester.name, user_path(invitation.requester) %>
      </div>
      <div>
        <%= link_to delete_friend_request_path(invitation),
                    method: :delete,
                    class: 'delete-request',
                    data: { confirm: "Delete #{invitation.requester.name}'s friend request?" } do %>
          <i class="fas fa-user-times"></i>
        <% end %>
        <%= link_to confirm_friend_request_path(invitation),
                    method: :post,
                    class: 'confirm-request' do %>
          <i class="fas fa-user-check"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/friends.html.erb
<h3><%= @user.name %>'s Friends</h3>

<div class='friends-container'>
  <% @friends.each do |friend| %>
    <div class='friend-full-row'>
      <div class='friend-row'>
        <%= avatar_thumbnail(friend, 'friend-list-avatar') %>
        <%= link_to friend.name, user_path(friend) %>
      </div>
      <div class='friendship-indicator'>
        <%= friendship_indicator(friend) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/likes.html.erb
<h3><%= @user.name %>'s Liked Posts</h3>

<div class='posts'>
  <%= render @posts %>
</div>

app/views/users/photos.html.erb
<h3><%= "#{@user.name}'s Photos" %></h3>


<div id='photos-container'>
  <% @posts.each do |post| %>
  <div>
    <a href=<%= post_path(post)%>>
      <%= image_tag post.photo %>
    </a>
  </div>
  <% end %>
</div>

app/views/users/posts.html.erb
<h3><%= "#{@user.name}'s Posts" %></h3>

<div class='posts'>
  <%= render @posts %>
</div>

app/views/users/show.html.erb
<div id='profile-summary'>
  <div class='profile-avatar'>
    <% if @user.avatar.attached? %>
      <%= link_to @user.avatar do %>
        <%= image_tag @user.avatar, class: 'profile-avatar' %>
      <% end %>
    <% end %>
  </div>

  <div class='friendship-indicator'>
    <%= friendship_indicator(@user) %>
  </div>

  <div class='basic-info'>
    <div class='profile-username'><%= @user.name %></div>

    <% unless @user.location.blank? %>
      <div class='info-row'>
        <ion-icon name="location-sharp"></ion-icon>
        <%= @user.location %>
      </div>
    <% end %>

    <% unless @user.birthday.blank? %>
      <div class='info-row'>
        <i class="fas fa-birthday-cake"></i>
        <%= @user.formatted_birthday %>
      </div>
    <% end %>

    <% [1, 2, 3].each do |n| %>
      <% unless @user.send("education#{n}").blank? %>
        <div class='info-row'>
          <ion-icon name="school-sharp"></ion-icon>
          <%= @user.send("education#{n}") %>
        </div>
      <% end %>
    <% end %>

    <% unless @user.occupation.blank? %>
      <div class='info-row'>
        <ion-icon name="briefcase-sharp"></ion-icon>
        <%= @user.occupation %>
      </div>
    <% end %>

    <% unless @user.website.blank? %>
      <div class='info-row'>
        <ion-icon name="globe-outline"></ion-icon>
        <%= valid_url?(@user.website) ? (link_to strip_protocol(@user.website), @user.website, target: :_blank) : @user.website %>
      </div>
    <% end %>
  
  </div>
</div>

<%= render @user.posts
                .left_outer_joins(:photo_attachment)
                .where( active_storage_attachments: { id: nil} )
                .order(created_at: :desc)
                .limit(4)
                .includes(:likes, comments: [:comments])
                .with_attached_photo %>

<%= link_to 'View all posts', user_posts_path(@user) %>

<hr>

<% posts = @user.posts
                .joins(:photo_attachment)
                .order(created_at: :desc)
                .limit(6)
                .with_attached_photo %>
<% if posts.exists? %>
  <div id='photos-container'>
    <% posts.each do |post| %>
      <div>
        <%= link_to post_path(post) do %>
          <%= image_tag post.photo %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<%= link_to 'View all photos', user_photos_path(@user) %>

<hr>

<span><%= "#{@user.name}'s friends" %></span>
<%= link_to '(see all)', user_friends_path(@user) %>
<% if @user.friends.exists? %>
  <div class='friends-container'>
    <% @user.friends.with_attached_avatar.limit(8).order("RANDOM()").each do |friend| %>
      <div class='friend-row'>
        <%= avatar_thumbnail(friend, 'friend-list-avatar') %>
        <%= link_to friend.name, user_path(friend) %>
      </div>
    <% end %>
  </div>
<% end %>

<hr>
<%= link_to "#{@user.name}'s Liked Posts", user_likes_path(@user) %>