config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: :show do
    get 'posts'
    get 'photos'
    get 'friends'
    get 'likes'
  end

  get 'profile/edit', to: 'users#edit_profile', as: :edit_profile
  patch 'profile/update', to: 'users#update_profile', as: :update_profile

  get '/friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :posts do
    resources :comments, only: [:new, :edit]
  end

  resources :comments, only: [:create, :update, :destroy]
  get 'posts/:comment_id/new', to: 'comments#new_reply', as: 'new_reply'
  get 'posts/:comment_id/edit', to: 'comments#edit_reply', as: 'edit_reply'

  resources :likes, only: [:create, :destroy]

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  delete 'unfriend', to: 'friendships#destroy', as: 'destroy_friendship'

  get 'about', to: 'static_pages#about'
  get 'search', to: 'static_pages#search'
  get 'odin/invincible', to: 'static_pages#odin_invincible'
  get 'odin/immutable', to: 'static_pages#odin_immutable'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  author_id  :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  include ActionView::Helpers::DateHelper

  belongs_to :author,
    class_name: :User

  has_many :likes,
    as: :likable,
    dependent: :destroy

  has_many :comments,
    -> { order(:created_at) },
    as: :commentable,
    dependent: :destroy

  has_one_attached :photo

  validate :contains_text_or_photo

  def history
    history = 
      if created_at > 4.days.ago
        time_ago_in_words(created_at) + ' ago'
      else
        created_at.strftime('%b %-d %Y')
      end
    (updated_at - created_at < 1) ? history : (history + '<i> (edited)</i>').html_safe
  end

  def total_comments
    comments.to_a.sum { |comment| 1 + comment.comments.length }
  end

  def get_post_or_photo_id
    # necessary in LikesController#referer_url_with_anchor for when likable is a comment
    id
  end

  private

  def contains_text_or_photo
    unless !body.empty? || photo.attached?
      errors.add(:base, :blank, message: 'Post must contain a text and/or photo.')
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :custom_authenticate_user!, only: :index
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :require_author!, except: [:index, :show, :new, :create]

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.new
    timeline_author_ids = current_user.friends.pluck(:id) << current_user.id
    @posts = Post.where('author_id IN (?)', timeline_author_ids)
                 .order(created_at: :desc)
                 .includes(:likes, comments: :comments, author: { avatar_attachment: :blob })
                 .with_attached_photo
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # not sure that this preloading is effective for a single record
    @post = Post.includes(
                   :likes,
                   comments: [
                     :likes,
                     author: { avatar_attachment: :blob},
                     comments: [
                        :likes,
                        author: { avatar_attachment: :blob }
                     ]
                   ]
                 )
                .find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html do
          flash.now[:alert] = "Error: #{@post.errors.full_messages.join}"
          render :new
        end
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html do
          flash.now[:alert] = "Error: #{@post.errors.full_messages.join}"
          render :edit
        end
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :photo)
    end

    def require_author!
      unless current_user.id == @post.author_id
        flash[:alert] = 'You are not authorized to edit this post!'
        redirect_to root_url
      end
    end

    def custom_authenticate_user!
      # avoids setting flash message for root url
      unless user_signed_in?
        flash.alert = 'You need to sign in or sign up before continuing.' unless request.env['PATH_INFO'] == '/'
        redirect_to new_user_session_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% submit = post.persisted? ? 'Update' : 'Post' %>
<% placeholder = post.photo.attached? ? 'Enter a caption...' : 'What\'s on your mind?' %>

<%= form_with(model: post, local: true) do |form| %>

      <%= form.text_area :body, placeholder: placeholder, autofocus: autofocus %>

      <% if post.photo.attached? %>
          <%= image_tag post.photo, class: 'form-photo' %>
      <% end %>

  <div class='post-buttons'>

    <div class="image-upload">
      <div class='hide-button'></div>
      <%= form.file_field :photo, direct_upload: true, id: 'photo-input' %>
      <label for="photo-input">
        <i class="far fa-file-image"></i>
      </label>
    </div>

    <div class="submit-wrapper">
      <%= form.submit submit, class: 'submit-post' %>
    </div>
  </div>
<% end %>
<br>

app/views/posts/_post.html.erb
<% show_page ||= false %>
<% edit ||= false %>
<% autofocus ||= false %>

<div id='post-<%= post.id %>' class='post'>  
  <div class='history'><%= post.history %></div>
  <div class='body'>
    <div class='body-text'><%= post.body %></div>
    <% if post.photo.attached? %>
      <%= link_to post.photo do %>
        <%= image_tag post.photo, class: 'post-photo' %>
      <% end %>
    <% end %>
  </div>
  <div class='author'><%= link_to post.author.name, user_url(post.author) %></div>
  <div class='post-links'>
    <%= link_to 'Show', post unless show_page %>
    <% if current_user.id == post.author_id %>
      <%= link_to 'Edit', edit_post_path(post) %>
      <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <div class='like'>
    <% like = post.likes.find { |like| like.user_id == current_user.id } %>
    <% if like %>
      <%= button_to like_path(like), method: :delete, class: 'hidden-button' do %>
        <i class='fas fa-thumbs-up liked'></i>
      <% end %>
    <% else %>
      <%= button_to likes_path, params: { like: { user_id: current_user, likable_id: post.id, likable_type: 'Post' } }, class: 'hidden-button' do %>
        <i class='fas fa-thumbs-up'></i>
      <% end %>
    <% end %>
    <%= post.likes.size %>
  </div>

  <div class='comment-icon'>
    <%= link_to 'Comment', new_post_comment_path(post) %>
    <%= link_to post, class: 'comment-link' do %>
      <ion-icon name="chatbubbles-outline" class='comments-icon'></ion-icon>
      <span class='comments-count'><%= post.total_comments %></span>
    <% end %>
  </div>

  <% if show_page && post.comments.length > 0 %>
    <div class='comments'>
      <% post.comments.each do |comment| %>
        <%= render comment, comment: comment, edit: edit, reply_to: reply_to %>
        <% if reply_to == comment.id %>
          <div class='comment-reply nest-reply'>
            <%= avatar_thumbnail(current_user, 'comment-avatar') %>
            <div class='reply-form'><%= render 'comments/form', comment: comment.comments.build, submit: 'Reply', autofocus: true %></div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  
  <% if show_page %>
    <div class='new-comment'>
      <%= avatar_thumbnail(current_user, 'comment-avatar') %>
      <div class='new-comment-form'><%= render 'comments/form', comment: post.comments.build, submit: 'Comment', autofocus: autofocus %></div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, autofocus: true %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', :back %>

app/views/posts/index.html.erb
<%= render 'form', post: @post, autofocus: false %>

<div class='posts'>
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post, autofocus: true %>

<%= link_to 'Cancel', posts_path %>

app/views/posts/show.html.erb
<% @edit ||= false %>
<% @autofocus ||= false %>
<% @reply_to ||= false %>
<%= render @post, show_page: true, comments: true, edit: @edit, reply_to: @reply_to, autofocus: @autofocus %>