config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: :show do
    get 'posts'
    get 'photos'
    get 'friends'
    get 'likes'
  end

  get 'profile/edit', to: 'users#edit_profile', as: :edit_profile
  patch 'profile/update', to: 'users#update_profile', as: :update_profile

  get '/friends', to: 'users#friends', as: :friends
  scope '/friends', as: :friends do
    get 'find', to: 'users#find_friends'
    get 'requests', to: 'users#friend_requests'
  end

  resources :posts do
    resources :comments, only: [:new, :edit]
  end

  resources :comments, only: [:create, :update, :destroy]
  get 'posts/:comment_id/new', to: 'comments#new_reply', as: 'new_reply'
  get 'posts/:comment_id/edit', to: 'comments#edit_reply', as: 'edit_reply'

  resources :likes, only: [:create, :destroy]

  resources :friend_requests, only: :create do
    member do
      post 'confirm'
      delete 'delete'
    end
  end

  delete 'unfriend', to: 'friendships#destroy', as: 'destroy_friendship'

  get 'about', to: 'static_pages#about'
  get 'search', to: 'static_pages#search'
  get 'odin/invincible', to: 'static_pages#odin_invincible'
  get 'odin/immutable', to: 'static_pages#odin_immutable'

  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
end

app/views/layouts/_friends_sidebar.html.erb
<div id='friends-sidebar'>
  <% suggestions =  current_user.no_contacts.with_attached_avatar.limit(3).order("RANDOM()") %>
  <% unless suggestions.empty? %>
    <div id='friend-suggestions'>
      <h4>Friend Suggestions</h4>
      <% suggestions.each do |friend| %>
        <div class='friend-full-row'>
          <div class='friend-row'>
            <%= avatar_thumbnail(friend, 'friend-list-avatar') %>
            <%= link_to friend.name, user_path(friend) %>
          </div>
          <div>
            <%= button_to friend_requests_path, method: :post, class: 'add-friend', params: { recipient_id: friend.id } do %>
              <i class="fas fa-user-plus"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <hr>
  <% end %>
  <h4>Friends</h4>
  <% current_user.friends.with_attached_avatar.order(:name).each do |friend| %>
    <div class='friend-row'>
      <%= avatar_thumbnail(friend, 'friend-list-avatar') %>
      <%= link_to friend.name, user_path(friend) %>
    </div>
  <% end %>
</div>

app/views/layouts/_profile_sidebar.html.erb
<div id='profile_sidebar'>
  <%= avatar(current_user, 'sidebar-avatar') %>
  <div class='sidebar-username'><%= current_user.name %></div>

  <%= link_to posts_path do %>
    <div class='profile-row'>
      <ion-icon name="newspaper-outline"></ion-icon>
      <span>Timeline</span>
    </div>
  <% end %>

  <%= link_to current_user do %>
    <div class='profile-row'>
      <ion-icon name="person-circle-outline"></ion-icon>
      <span>Profile</span>
    </div>
  <% end %>

  <%= link_to edit_profile_path do %> 
    <div class='profile-row'>
      <ion-icon name="color-palette-outline"></ion-icon>
      <span>Edit Profile</span>
    </div>
  <% end %>

  <%= link_to friends_requests_path do %>
    <div class='profile-row'>
      <% notifications = current_user.friend_invitations.count %>
      <ion-icon name="flag-outline"></ion-icon>
      <span>Friend Requests<%= " (#{notifications})" if notifications > 0 %></span>
    </div>
  <% end %>

  <%= link_to friends_path do %>
    <div class='profile-row'>
      <ion-icon name="people-outline"></ion-icon>
      <span>Friends</span>
    </div>
  <% end %>

  <%= link_to friends_find_path do %>
    <div class='profile-row'>
      <ion-icon name="telescope-outline"></ion-icon>
      <span>Find Friends</span>
    </div>
  <% end %>

  <%= link_to user_posts_path(current_user) do %>
    <div class='profile-row'>
      <ion-icon name="documents-outline"></ion-icon>
      <span>My Posts</span>
    </div>
  <% end %>

  <%= link_to user_photos_path(current_user) do %>
    <div class='profile-row'>
      <ion-icon name="images-outline"></ion-icon>
      <span>My Photos</span>
    </div>
  <% end %>

  <%= link_to user_likes_path(current_user) do %>
    <div class='profile-row'>
      <ion-icon name="heart-outline"></ion-icon>
      <span>Liked Posts</span>
    </div>
  <% end %>

  <hr>
  <%= link_to new_post_path do %>
    <div class='profile-row'>
      <ion-icon name="create-outline"></ion-icon>
      <span>New Post</span>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialScrolls</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/07b0558508.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Xanh+Mono&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path("favicon.ico") %>

  </head>

  <body>
    <header>
      <div class='header-left'>
        <button class='header-button border-right border-left'>
          <%= link_to root_path, class: 'header-item' do %>
            <i class="fas fa-scroll"></i>
            <span>Social Scrolls</span>
          <% end %>
        </button><!--
        --><button class='header-button border-right'>
          <%= link_to 'About', about_path, class: 'header-item' %>
        </button><!--
        --><div class='search-form border-right'>
            <%= render 'static_pages/search_form' %>
         </div>
      </div>
      <div class='header-right'>
        <button class='header-button border-right border-left'>
          <%= link_to 'Account', edit_user_registration_path, class: 'header-item' %>
        </button><!--
        <% if user_signed_in? %>
          <% notifications = current_user.friend_invitations.count %>
          --><button class='header-button border-right'>
          <%= link_to friends_requests_path, class: 'header-item' do %>
            <% if notifications > 0 %>
              <ion-icon name="flag" id='flag' class='notifications'></ion-icon><!--
              --><sup class='notifications'><%= notifications %></sup>
            <% else %>
              <ion-icon name="flag"></ion-icon>
            <% end %>
          <% end %>
          </button><!--
          --><button class='header-button border-right'>
            <%= link_to 'Logout', destroy_user_session_path, class: 'header-item', method: :delete %>
          </button>
        <% else %>
          --><button class='header-button border-right'>
            <%= link_to 'Login', new_user_session_path, class: 'header-item' %>
          </button><!--
          --><button class='header-button border-right'>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'header-item' %>
          </button>
        <% end %>
      </div>
    </header>
    <% if notice || alert %>
      <div class='flash-container'>
        <% if notice %>
          <div id="notice"><%= notice %></div>
        <% end %>
        <% if alert %>
          <div class="alert"><%= alert %></div>
        <% end %>
      </div>
    <% end %>
    <div class='page-body'>
      <style> <%= yield :stylesheets %> </style>
      <%= render 'layouts/profile_sidebar' if user_signed_in? %>
      <div class='main <%= yield :main_wrapper %>'>
        <%= yield %>
      </div>
      <%= render 'layouts/friends_sidebar' if user_signed_in? %>
    </div>

    <script type="module" src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/layouts/devise.html.erb
<% content_for :stylesheets do %>
    #profile_sidebar {display: none;}
    #friends-sidebar {display: none;}
    .main { margin-left: auto; margin-right: auto; }
<% end %>

<%= content_for :main_wrapper, 'devise-wrapper' %>

<%= render :template => "layouts/application" %>